server:
  port: 9092

spring:
  application:
    name: product-service

# Using Mongo DB Atlas cloud
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: PRODUCTS
      auto-index-creation: true

  security:
    user:
      name: boot
      password: spring    

user:
  service:
    url: ${ECOM_USER_SERVICE_URL}

# logging:
#   level:
#     org:
#       springframework:
#         security: TRACE